# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "gtar")
set(gtar_VERSION "0.0.0")
set(required_pkgs
  "atk {nolink}"
  "cairo {nolink}"
  "config {nocheck,nolink}"
  "gdk-3.0 {nolink}"
  "gdk-pixbuf-2.0 {nolink}"
  "gio-2.0"
  "glib-2.0"
  "gobject-2.0"
  "gtk+-3.0"
  "pango {nolink}"
  "pangocairo {nolink}"
  "posix {nocheck,nolink}"
  "x11 {nolink}"
)
set(srcfiles
  "src/add_progress.vala"
  "src/extract-dialog.vala"
  "src/file_viewer.vala"
  "src/main.vala"
  "src/progress.vala"
  "src/properties_window.vala"
  "src/verify_window.vala"
)
set(vapifiles
  "vapi/config.vapi"
)
set(uifiles
  "ui/add.ui"
  "ui/extra.ui"
  "ui/menu.ui"
  "ui/progress.ui"
  "ui/properties.ui"
)
